- name : Configure Docker on EC2 Instances
  hosts : all
  become: true
  connection : ssh
  tasks : 
  - name: updating apt
    command : sudo apt-get update

  - name : Install Docker
    command : sudo apt-get install -y docker.io
    become : yes
    become_user : root

  - name : Start Docker Service
    command : sudo systemctl start docker  
    become : yes
    become_user : root
  
  - name : Pull the docker image
    command : docker pull rushanksam/insurance_project:1.0
    become : yes
    become_user : root

  - name : Deploy the app using image
    command : docker -d -p 8085:8081 rushanksam/insurance_project:1.0
    become : yes
    become_user : root
